---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1npdruy3nx2yr0h6yjmpffpsesszj7qldnsrpxt0sdrxwqsls85eq07l56y"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1npdruy3nx2yr0h6yjmpffpsesszj7qldnsrpxt0sdrxwqsls85eq07l56y"
