apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ufkMlqW3BlHFqFAS/IYXUs31/TfboRuDCrcGrV4MmDYaM9XK,iv:Dg6C9F11Htu3hS5OTubIFbfbC1HidRqQRpUanPwSufM=,tag:KKHrCABdcykTYsMbbyrQTw==,type:str]
    credentials.json: ENC[AES256_GCM,data:AU7qdmp63JV+8k6YK3X/Nk2w+eJLEmoB0iXx4X0+elk8BIPAhA3LWbJwxnFl2ZWzZexTbNQ+rNexIJrKkBXNOnbcnsQcvYMSAbilcyDaHaC2PwywJ1RF0sllWl8HVLVx0IWX/axTxZxW/c1djiiufs1s/JgXdfyQocNYSbsbX+4JGxFndabTnsi+mQYimvVj9/TI8moOmC0/nl3/LmDhDPQPGR2b0Oy+Imbt6dat5A==,iv:eo//dbFVQkEdbgOdEyNz6UlESPbSkQ7/hjUf3bP8huw=,tag:4Y4Sg5EM2ChEbgWqyWIEeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npdruy3nx2yr0h6yjmpffpsesszj7qldnsrpxt0sdrxwqsls85eq07l56y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bU03czJITFA1ejUvUjJx
            VUNNZ0ZiYUt6SXlSRlEzK2Y0M2lCZGVJSEhvCnF1eHFCRmE2NVlaNjBWcGt4VDZS
            ME9VSnJVbmhRWlFSNHV3MkxPZzdFbVEKLS0tIGZGL3pvOC9BV3R1REd6UDYyamxx
            RU9ncmI1QnllZHJPbEtCSkpRTHJUcjQKeQt7yZwvt450/gGbEHYH96/EYybHdj1Z
            bMm55c7JYrPRua0L9i2c7O071J5VunBXKcjep08yLDljFSNvIRj6xA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-26T02:43:34Z"
    mac: ENC[AES256_GCM,data:mFSXxsL5sr9AkWxmnaqXha8orVaX2Z1AMxsEmxrAAuSUpBGxPDcFU0gLJbqNXupW8D1wJarjC/u63/bERRNS7thzq+fJDtX8LEkv8ncV3wfLspjiC7s8+HzRWAPSiTRSdXVbZUOx0rjXv3DoCUX5/tdErrUCqOJiKG2olWAhjiU=,iv:uKFEziqIg3O+C180BE5nbCssDt+uc+AWg+amnLrQxJc=,tag:lDYFxqERO4/rLxWd1IDmLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
