apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:lcqVrjsmfo6oe9mLWCyN+1Etrrkokaz9PKz7mMEUzOC1aed5,iv:isd1yl0AszdReaqkFVuWCqGOrpAzqJy4GisIdawe6Wg=,tag:d/YpDUhsmIk8veIJoFJi5Q==,type:str]
    credentials.json: ENC[AES256_GCM,data:LUN760pkLEQzR70D7AWMJU74Xa2wK65hIbLhPFxDMdnVb9Pw6JGzLnWdkRYX6GEElgsIxmIlv+QovRHFpt1P4/S8V5jsMk8dVYAf60jqwj0VB1Qva1XHYRkGOyDnmirUNkmgFi11EilF/C5LcLxykVHpRrZepTvb1ntdkUSdJjM5e6SwRwvERPo5jcqPin3pbpc0AGontuut4c1we44PKQ9FUXGiTxUPQsaHK02ysg==,iv:OZ5wotuG6nEXkiYgm9bPqRi14dVR6/DpeD/xLbZ1w0Q=,tag:hZ7rvvw/sOFbugLIGiUonQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npdruy3nx2yr0h6yjmpffpsesszj7qldnsrpxt0sdrxwqsls85eq07l56y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhNlhVVmlibFE0V1lzVzBh
            OW9Gc3p0QmFvY2RTZnJXM3BNT0k0ZXRoT1IwCkVOYzJMdnY0cC9pUUlxN1FLOEtv
            U1NTL1Y1eVpGMXI3azgyMitFaFBqNWMKLS0tIFQyRlAzaEMxbVcvV3dSczByODkr
            TnJlaVkwR0lUdXNmeUxIc0UyVEZFR3MKUNoyCcQKNAZzxZOviLUoU5hBxGGYbBn+
            obX1Rro71VtC5AA6mk302O+ciZLYZo1EOJH9f+yICxrM/O+2nB/9Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-26T04:36:24Z"
    mac: ENC[AES256_GCM,data:6c/uLQ2tsGuHjH4eWaP4Hfz/5/sgqHmLviuyT0V/oDur+78IuUP76hIkrn4DEfukCrR5D1kSU/3LRoO0GzzuyxOqwHMI7AUDaKRwcW7PP5cKYV4jpnZ0XeKYggRzKZcda303AYqPuSwATvHGQrzsINod61MJHDDak6MTDddO4so=,iv:8jx+tpv+2QeL7QIixOZwykpXJWUB7uQTG/BSxEEWIo8=,tag:b5Yv08lJRoCRyoE8TaV2bA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
