apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:44ewR+goUGPMR2E3UInWf/jA/z77ZJPY,iv:E0Dwunu/bbodYrMVfdKYZ2vQUE/knkULhWGSTut7uKI=,tag:Y9jV87GHeEQV0EmH18omsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npdruy3nx2yr0h6yjmpffpsesszj7qldnsrpxt0sdrxwqsls85eq07l56y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOE1Pajl5NjNuQytVemdZ
            Y1ptM2lMaTdXMW5lQ0NPeDhZR3NlZHJtNkRzCnozbkxkR2h3MTIrT1FZaXRPcVJn
            TTVCVll6dmlMcjN4dmVDS2V3ZEdJcVkKLS0tIG51UFdvb21YdXRqSVdCTzA3WTMy
            UkpQMTRkL0ZpbkZEOERnNm92eHNVZTQKdPTh8o6PepWAhcoJhAyKMXDa4ua3Tp+k
            r1lFFedF/HiBSWvbmQMCZPxA1+ix7cklUXrgU3+sHUNFsawBa3fYqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-26T06:15:08Z"
    mac: ENC[AES256_GCM,data:lj1IpaOfGpEYlziB/hYWtCkeflUOK+NvPguunbk3ai9zpmfmiq0l5QjqQ0HgMnPyBoPSLvu5m/0fHcZfkzuCaO8sxTKp8UBBZs4JyaDp2ocBKqmeLy/OsMpJNq8wCvbH6RZRgtQoHzm74hcfu7jxEvHJkb85aC/oYP6NtyoRNSM=,iv:rBw/outfP/jth0zvTIMNDGmJfykdQ5koX8Y2FgttcFE=,tag:u7aFukqov58AaxlS9nOrkw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
