apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:NNaNOOqCe36gx2CXpLuh,iv:3OvQEnICaHGEC0QHZJxHlA0bwz51cSvIMU0Y/HENIYc=,tag:ev9yMUSx3RfAMEa3HMKG5g==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:R4P75CjSdsXcLfA9nJpFVNCveIAE/TBODQ==,iv:ox61WEOZqVc+bB6Cj3torOE5lwpxwT0zxQiN56AcwLQ=,tag:2FmiO4NGMCWbbgtw9W668Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:C85iiBRuCdll9gi3tPR7vF0zJiFGVrAabqRrMvw6S5RPeQpT,iv:9BW3q+6Zc+FqEXFBI0UfbwZNxl+nAEyI0k/pS4yeYjs=,tag:2DTC3wDCotumowiaU/MG4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npdruy3nx2yr0h6yjmpffpsesszj7qldnsrpxt0sdrxwqsls85eq07l56y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoS1JzWVZPazhianVqMGZk
            NU5FQ25SY20xVjVqNG0waGY5VldiYjQxUEUwCnYzdzlsWWx0eGRUODlPMkw2QzRq
            WDVRYmN3K3VycUhMZ2hpV2wrZ1EwWmcKLS0tIE5DZkNqc3llNkFnRUg5WFB1bTBw
            bWRncDQrc2hQSlZPNlVlTzRkL1I1UFkK1qbNhGXkDf7xOh9HvDBYw9h82mY0+tsM
            geDwj2qdsXL5wsrhFv5Qt/logEiuQgu7H9owhnz1ppL4qrHPql5OIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-26T06:15:08Z"
    mac: ENC[AES256_GCM,data:VMieV//R/jHKB9osC4G3UlW8bCnmqGNjTTC/K+sQGanHNveYstiER+uWntANHcXehijCg5nrpjfS2NDRBVAkfjfx6ZDIlaHOqHmxPHS1Oazh83yGSW/QJykN+U1fWw6647K4kHc5bVfjEBekKC3vSo9zLZzTTsbrUNtV36mAjl8=,iv:hYQ64VUYtEt/zA/xfk7+s/A3FVDLj92Dxmz3/M57fBg=,tag:i3X2IfW3bAP5S5GYPNteEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
